const Icons = {
  bold: "material-symbols:format-bold",
  italic: "material-symbols:format-italic-rounded",
  strike: "material-symbols:strikethrough-s",
  code: "material-symbols:code",
  paragraph: "material-symbols:format-paragraph",
  h1: "material-symbols:format-h1-rounded",
  h2: "material-symbols:format-h2-rounded",
  h3: "material-symbols:format-h3-rounded",
  h4: "material-symbols:format-h4-outline-rounded",
  h5: "material-symbols:format-h5-rounded",
  h6: "material-symbols:format-h6-rounded",
  bulletList: "fluent:text-bullet-list-ltr-16-filled",
  orderedList: "mingcute:list-ordered-line",
  codeBlock: "ci:window-code-block",
  blockquote: "grommet-icons:block-quote",
  horizontalRule: "codicon:horizontal-rule",
  undo: "gg:undo",
  redo: "ci:redo",
  leftAlign: "material-symbols:format-align-left-rounded",
  centerAlign: "material-symbols:format-align-center-rounded",
  rightAligh: "material-symbols:format-align-right-rounded",
  highlight: "pajamas:highlight",
  justify: "material-symbols:format-align-justify-rounded",
  link: "material-symbols:link",
  unlink: "material-symbols:link-off-rounded",
  removeStyles: "mdi:signature-text",
  underline: "humbleicons:underline",
};
export default Icons;
